export const GET_ERRORS = "GET_ERRORS";
export const SET_USER_DATA = "SET_USER_DATA";
export const GET_STUDENTS_DATA = "GET_STUDENTS_DATA";
export const SET_STUDENTS_LOADING = "SET_STUDENTS_LOADING";
